# Generated by Django 2.1.2 on 2019-03-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
